version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - /var/tmp/docker/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge